services:
  express-frontend:
    build:
      context: .
      dockerfile: ./Business-Layer/Express-Server/Dockerfile
    container_name: express-server
    ports:
      - "80:80"
    depends_on:
      n8n:
        condition: service_healthy
    networks:
    - n8n-network
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    container_name: ollama
    networks:
      - n8n-network

    command: >
      /bin/sh -c "
      /bin/ollama pull llama3-groq-tool-use:8b 
      "
    volumes:
      - ollama_data:/root/.ollama

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    networks:
      - n8n-network
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_IMPORT_EXPORT_DIR=/data
      - N8N_IMPORT_ON_START=full
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - n8n_data:/home/node/.n8n
      - ./Business-Layer:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5678/healthz"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  n8n-network:

volumes:
  ollama_data:
  n8n_data: